services:
  postgres:
    image: postgres:16
    container_name: askthesite-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: askthesite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  redis:
    image: redis:7
    container_name: askthesite-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      target: dev # change to prod for production
    container_name: askthesite-api
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis
    command: sh -c "pnpm dev:watch"

  worker:
    build:
      context: ./worker
      target: dev
    container_name: askthesite-worker
    env_file:
      - ./worker/.env
    depends_on:
      - postgres
      - redis
    
    command: sh -c "pnpm dev:watch"

volumes:
  postgres_data:
