services:
  # web:
  #   build:
  #     context: ./
  #     dockerfile: web/Dockerfile
  #     target: development
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - API_URL=http://api:8000
  #     - WATCHPACK_POLLING=true
  #   volumes:
  #     - ./web:/app/web
  #     - /app/web/node_modules
  #   depends_on:
  #     - api
  #   networks:
  #     - ats-network

  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
      target: development
    ports:
      - "8000:8000"
    
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app/api
      - ./database:/app/database
      - /app/api/node_modules
      - /app/database/node_modules
    depends_on:
      - ats_pg
      - ats_rd
    networks:
      - ats-network

  # worker:
  #   build:
  #     context: ./
  #     dockerfile: worker/Dockerfile
  #     target: development
  #   ipc: host
  #   init: true
  #   cap_add:
  #     - SYS_ADMIN 
  #   env_file:
  #     - ./worker/.env
  #   volumes:
  #     - ./worker:/app/worker
  #     - ./database:/app/database
  #     - /app/worker/node_modules
  #     - /app/database/node_modules
  #   depends_on:
  #     - ats_pg
  #     - ats_rd
  #   networks:
  #     - ats-network

  ats_pg:
    image: postgres:16
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=ats
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ats-network

  # ats_rd:
  #   image: redis:alpine
    # restart: always
    # ports:
    #   - "6379:6379"
    # networks:
    #   - ats-network

volumes:
  postgres_data:

networks:
  ats-network:
    driver: bridge
