services:
  postgres:
    image: postgres:16
    container_name: asktheweb-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asktheweb
    ports:
      - "5432:5432"
    
    volumes:
      - posgres_data:/var/lib/postgresql/data
    
  
  redis:
    image: redis:7
    container_name: asktheweb-redis
    ports:
      - "6379:6379"
    
  
  api:
    build:
      context: ./api
    container_name: asktheweb-api

    ports:
      - "4000:4000"
    
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/asktheweb
      REDIS_URL: redis://localhost:6379
    
    depends_on:
      - postgres
      - redis

  
  worker:
    build:
      context: ./apps/worker
    container_name: askthesite-worker

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/asktheweb
      REDIS_URL: redis://localhost:6379

    depends_on:
      - postgres
      - redis

  
  web:
    build:
      context: ./apps/web
    container_name: askthesite-web

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000

    depends_on:
      - api
  
volumes:
  posgres_data:


