services:
  postgres:
    image: postgres:16
    container_name: askthesite-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: askthesite
    ports:
      - "5432:5432"
    
    volumes:
      - posgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  
  redis:
    image: redis:7
    container_name: askthesite-redis
    ports:
      - "6379:6379"
    
  
  api:
    build:
      context: ./api
    container_name: askthesite-api

    ports:
      - "4000:4000"
    
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/askthesite
      REDIS_URL: redis://localhost:6379
    
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
      - /app/node_modules

  
  worker:
    build:
      context: ./worker
    container_name: askthesite-worker

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/askthesite
      REDIS_URL: redis://localhost:6379

    depends_on:
      - postgres
      - redis
    volumes:
      - ./worker:/app
      - /app/node_modules

  
  web:
    build:
      context: ./web
    container_name: askthesite-web

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000

    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
  
volumes:
  posgres_data:


